site_name: Knut - Code transformation via scripts
site_description: Knut Documentation - Automation tool for code transformation using scripts
site_author: Klarälvdalens Datakonsult AB (KDAB)
site_url: https://kdab.github.io/knut/
copyright: "Copyright &copy; Klar&auml;lvdalens Datakonsult AB (KDAB)<br>Trusted Software Excellence<br><a href='https://www.kdab.com'>https://www.kdab.com/</a>"
repo_url: https://github.com/KDAB/Knut
repo_name: Knut

theme:
  name: material
  palette:
    - scheme: kdab
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  logo: assets/transparentWhiteKDAB.svg

extra_css:
  - stylesheets/extra.css

use_directory_urls: false

nav:
    - Home: index.md
    - Getting Started:
        - Overview: getting-started/overview.md
        - Writing a script: getting-started/script.md
        - Syntax tree queries: getting-started/treesitter.md
        - Command line interface: getting-started/cli.md
        - User interface: getting-started/gui.md
    - Contributing:
        - Getting involved: contributing/getting-involved.md
        - Architecture: contributing/architecture.md
        - Unit tests: contributing/unit-tests.md
    - Script API:
# DO NOT EDIT: THIS IS DONE AUTOMATICALLY
# -->
        - Knut Module:
            - Document: API/knut/document.md
            - Project: API/knut/project.md
            - CodeDocument:
                - CodeDocument: API/knut/codedocument.md
                - ClassSymbol: API/knut/classsymbol.md
                - FunctionArgument: API/knut/functionargument.md
                - FunctionSymbol: API/knut/functionsymbol.md
                - QueryCapture: API/knut/querycapture.md
                - QueryMatch: API/knut/querymatch.md
                - Symbol: API/knut/symbol.md
            - CppDocument:
                - CppDocument: API/knut/cppdocument.md
                - DataExchange: API/knut/dataexchange.md
                - DataExchangeEntry: API/knut/dataexchangeentry.md
                - MessageMap: API/knut/messagemap.md
                - MessageMapEntry: API/knut/messagemapentry.md
            - QtTsDocument:
                - QtTsDocument: API/knut/qttsdocument.md
                - QtTsMessage: API/knut/qttsmessage.md
            - QtUiDocument:
                - QtUiDocument: API/knut/qtuidocument.md
                - QtUiWidget: API/knut/qtuiwidget.md
            - RcDocument:
                - RcDocument: API/knut/rcdocument.md
                - Action: API/knut/action.md
                - Asset: API/knut/asset.md
                - Menu: API/knut/menu.md
                - MenuItem: API/knut/menuitem.md
                - Ribbon: API/knut/ribbon.md
                - RibbonCategory: API/knut/ribboncategory.md
                - RibbonContext: API/knut/ribboncontext.md
                - RibbonElement: API/knut/ribbonelement.md
                - RibbonMenu: API/knut/ribbonmenu.md
                - RibbonPanel: API/knut/ribbonpanel.md
                - Shortcut: API/knut/shortcut.md
                - String: API/knut/string.md
                - ToolBar: API/knut/toolbar.md
                - ToolBarItem: API/knut/toolbaritem.md
                - Widget: API/knut/widget.md
            - TextDocument:
                - TextDocument: API/knut/textdocument.md
                - Mark: API/knut/mark.md
                - RangeMark: API/knut/rangemark.md
                - TextLocation: API/knut/textlocation.md
                - TextRange: API/knut/textrange.md
            - Items:
                - Script: API/knut/script.md
                - ScriptDialog: API/knut/scriptdialog.md
            - Utilities:
                - Dir: API/knut/dir.md
                - File: API/knut/file.md
                - FileInfo: API/knut/fileinfo.md
                - Message: API/knut/message.md
                - Settings: API/knut/settings.md
                - UserDialog: API/knut/userdialog.md
                - Utils: API/knut/utils.md
                - QDirValueType: API/knut/qdirvaluetype.md
                - QFileInfoValueType: API/knut/qfileinfovaluetype.md
        - Knut.Test Module:
            - TestCase: API/knut.test/testcase.md
            - TestUtil: API/knut.test/testutil.md
# <--

markdown_extensions:
    - toc:
        permalink: "#"
        toc_depth: 3
    - admonition
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.tabbed
    - attr_list

plugins:
    - search:
        separator: '[\s\-\.]+'
    - build_plantuml:
          render: "server"
          server: "http://www.plantuml.com/plantuml"
          output_format: "svg"
          diagram_root: "docs/assets"
          output_folder: "."
          input_folder: "."
          input_extensions: ""
