site_name: Knut - Code transformation via scripts
site_description: Knut Documentation - Automation tool for code transformation using scripts
site_author: Klarälvdalens Datakonsult AB (KDAB)
site_url: https://kdab.github.io/knut/
copyright: "Copyright &copy; Klar&auml;lvdalens Datakonsult AB (KDAB)<br>Trusted Software Excellence<br><a href='https://www.kdab.com'>https://www.kdab.com/</a>"
repo_url: https://github.com/KDAB/Knut
repo_name: Knut

theme:
  name: material
  palette:
    - scheme: kdab
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  logo: assets/transparentWhiteKDAB.svg

extra_css:
  - stylesheets/extra.css

use_directory_urls: false

nav:
    - Home: index.md
    - Getting Started:
        - Overview: getting-started/overview.md
        - Writing a script: getting-started/script.md
        - Syntax tree queries: getting-started/treesitter.md
        - Command line interface: getting-started/cli.md
        - User interface: getting-started/gui.md
    - Contributing:
        - Getting involved: contributing/getting-involved.md
        - Architecture: contributing/architecture.md
        - Unit tests: contributing/unit-tests.md
    - Script API:
# DO NOT EDIT: THIS IS DONE AUTOMATICALLY
# -->
        - Script Module:
            - Document: API/script/document.md
            - Project: API/script/project.md
            - CodeDocument:
                - CodeDocument: API/script/codedocument.md
                - ClassSymbol: API/script/classsymbol.md
                - FunctionArgument: API/script/functionargument.md
                - FunctionSymbol: API/script/functionsymbol.md
                - QueryCapture: API/script/querycapture.md
                - QueryMatch: API/script/querymatch.md
                - Symbol: API/script/symbol.md
            - CppDocument:
                - CppDocument: API/script/cppdocument.md
                - DataExchange: API/script/dataexchange.md
                - DataExchangeEntry: API/script/dataexchangeentry.md
                - MessageMap: API/script/messagemap.md
                - MessageMapEntry: API/script/messagemapentry.md
            - QtTsDocument:
                - QtTsDocument: API/script/qttsdocument.md
                - QtTsMessage: API/script/qttsmessage.md
            - QtUiDocument:
                - QtUiDocument: API/script/qtuidocument.md
                - QtUiWidget: API/script/qtuiwidget.md
            - RcDocument:
                - RcDocument: API/script/rcdocument.md
                - Action: API/script/action.md
                - Asset: API/script/asset.md
                - Menu: API/script/menu.md
                - MenuItem: API/script/menuitem.md
                - Ribbon: API/script/ribbon.md
                - RibbonCategory: API/script/ribboncategory.md
                - RibbonContext: API/script/ribboncontext.md
                - RibbonElement: API/script/ribbonelement.md
                - RibbonMenu: API/script/ribbonmenu.md
                - RibbonPanel: API/script/ribbonpanel.md
                - Shortcut: API/script/shortcut.md
                - String: API/script/string.md
                - ToolBar: API/script/toolbar.md
                - ToolBarItem: API/script/toolbaritem.md
                - Widget: API/script/widget.md
            - TextDocument:
                - TextDocument: API/script/textdocument.md
                - Mark: API/script/mark.md
                - RangeMark: API/script/rangemark.md
                - TextLocation: API/script/textlocation.md
                - TextRange: API/script/textrange.md
            - Items:
                - Script: API/script/script.md
                - ScriptDialog: API/script/scriptdialog.md
            - Utilities:
                - Dir: API/script/dir.md
                - File: API/script/file.md
                - FileInfo: API/script/fileinfo.md
                - Message: API/script/message.md
                - Settings: API/script/settings.md
                - UserDialog: API/script/userdialog.md
                - Utils: API/script/utils.md
                - QDirValueType: API/script/qdirvaluetype.md
                - QFileInfoValueType: API/script/qfileinfovaluetype.md
        - Script.Test Module:
            - TestCase: API/script.test/testcase.md
            - TestUtil: API/script.test/testutil.md
# <--

markdown_extensions:
    - toc:
        permalink: "#"
        toc_depth: 3
    - admonition
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.tabbed
    - attr_list

plugins:
    - search:
        separator: '[\s\-\.]+'
    - build_plantuml:
          render: "server"
          server: "http://www.plantuml.com/plantuml"
          output_format: "svg"
          diagram_root: "docs/assets"
          output_folder: "."
          input_folder: "."
          input_extensions: ""
