version = 1
SPDX-PackageName = "knut"
SPDX-PackageSupplier = "<info@kdab.com>"
SPDX-PackageDownloadLocation = "https://github.com/KDAB/knut/"

[[annotations]]
path = [".pre-commit-config.yaml", ".codespellrc", ".clangd", "**.clang-format", ".clazy", ".gitattributes", ".github/workflows/documentation.yml", ".gitignore", ".gitmodules", ".krazy", "knut.code-workspace", ".github/**.yml", "mkdocs.yml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["**.md", "docs/API/mapping.txt", "docs/**.png", "docs/**.puml", "docs/**.gif", "docs/**.svg", "docs/**.css"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = ["**.json", "**.ui", "**.qrc", "**.rc", "**.xml", "src/**.png", "src/**.ico", "version.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "GPL-2.0-only OR GPL-3.0-only"

[[annotations]]
path = "test_data/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "GPL-2.0-only OR GPL-3.0-only"

[[annotations]]
path = ["test_data/rcfiles/cryEdit/Resource.h", "test_data/rcfiles/luaDebugger/resource.h"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Amazon.com, Inc. or its affiliates or its licensors"
SPDX-License-Identifier = "Apache-2.0 OR MIT"

[[annotations]]
path = "qt6.natvis"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 The Qt Company Ltd."
SPDX-License-Identifier = "GPL-3.0-only OR LicenseRef-Qt-Commercial"

[[annotations]]
path = "src/gui/gui/**.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "The Pictogrammers"
SPDX-License-Identifier = "Apache-2.0"
