#ifndef LOGGING_H
#define LOGGING_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(TOKENIZER)
Q_DECLARE_LOGGING_CATEGORY(PARSER)
Q_DECLARE_LOGGING_CATEGORY(CONVERTER)
Q_DECLARE_LOGGING_CATEGORY(JSRUNNER)

#endif // LOGGING_H
