// File generated by spec2cpp tool
// DO NOT MAKE ANY CHANGES HERE

#pragma once

#include "json.h"
#include "types.h"

namespace Lsp {

JSONIFY_ENUM(ResourceOperationKind,
             {
                 {ResourceOperationKind::Create, "create"},
                 {ResourceOperationKind::Rename, "rename"},
                 {ResourceOperationKind::Delete, "delete"},
             })

JSONIFY_ENUM(FailureHandlingKind,
             {
                 {FailureHandlingKind::Abort, "abort"},
                 {FailureHandlingKind::Transactional, "transactional"},
                 {FailureHandlingKind::TextOnlyTransactional, "textOnlyTransactional"},
                 {FailureHandlingKind::Undo, "undo"},
             })

JSONIFY_ENUM(MarkupKind,
             {
                 {MarkupKind::PlainText, "plaintext"},
                 {MarkupKind::Markdown, "markdown"},
             })

JSONIFY_ENUM(TraceValue,
             {
                 {TraceValue::Off, "off"},
                 {TraceValue::Messages, "messages"},
                 {TraceValue::Verbose, "verbose"},
             })

JSONIFY_ENUM(FileOperationPatternKind,
             {
                 {FileOperationPatternKind::File, "file"},
                 {FileOperationPatternKind::Folder, "folder"},
             })

JSONIFY_ENUM(CodeActionKind,
             {
                 {CodeActionKind::Empty, ""},
                 {CodeActionKind::QuickFix, "quickfix"},
                 {CodeActionKind::Refactor, "refactor"},
                 {CodeActionKind::RefactorExtract, "refactor.extract"},
                 {CodeActionKind::RefactorInline, "refactor.inline"},
                 {CodeActionKind::RefactorRewrite, "refactor.rewrite"},
                 {CodeActionKind::Source, "source"},
                 {CodeActionKind::SourceOrganizeImports, "source.organizeImports"},
             })

JSONIFY_ENUM(FoldingRangeKind,
             {
                 {FoldingRangeKind::Comment, "comment"},
                 {FoldingRangeKind::Imports, "imports"},
                 {FoldingRangeKind::Region, "region"},
             })

JSONIFY_ENUM(SemanticTokenTypes,
             {
                 {SemanticTokenTypes::Namespace, "namespace"},
                 {SemanticTokenTypes::Type, "type"},
                 {SemanticTokenTypes::Class, "class"},
                 {SemanticTokenTypes::Enum, "enum"},
                 {SemanticTokenTypes::Interface, "interface"},
                 {SemanticTokenTypes::Struct, "struct"},
                 {SemanticTokenTypes::TypeParameter, "typeParameter"},
                 {SemanticTokenTypes::Parameter, "parameter"},
                 {SemanticTokenTypes::Variable, "variable"},
                 {SemanticTokenTypes::Property, "property"},
                 {SemanticTokenTypes::EnumMember, "enumMember"},
                 {SemanticTokenTypes::Event, "event"},
                 {SemanticTokenTypes::Function, "function"},
                 {SemanticTokenTypes::Method, "method"},
                 {SemanticTokenTypes::Macro, "macro"},
                 {SemanticTokenTypes::Keyword, "keyword"},
                 {SemanticTokenTypes::Modifier, "modifier"},
                 {SemanticTokenTypes::Comment, "comment"},
                 {SemanticTokenTypes::String, "string"},
                 {SemanticTokenTypes::Number, "number"},
                 {SemanticTokenTypes::Regexp, "regexp"},
                 {SemanticTokenTypes::Operator, "operator"},
             })

JSONIFY_ENUM(SemanticTokenModifiers,
             {
                 {SemanticTokenModifiers::Declaration, "declaration"},
                 {SemanticTokenModifiers::Definition, "definition"},
                 {SemanticTokenModifiers::Readonly, "readonly"},
                 {SemanticTokenModifiers::Static, "static"},
                 {SemanticTokenModifiers::Deprecated, "deprecated"},
                 {SemanticTokenModifiers::Abstract, "abstract"},
                 {SemanticTokenModifiers::Async, "async"},
                 {SemanticTokenModifiers::Modification, "modification"},
                 {SemanticTokenModifiers::Documentation, "documentation"},
                 {SemanticTokenModifiers::DefaultLibrary, "defaultLibrary"},
             })

JSONIFY_ENUM(TokenFormat,
             {
                 {TokenFormat::Relative, "relative"},
             })

JSONIFY_ENUM(UniquenessLevel,
             {
                 {UniquenessLevel::Document, "document"},
                 {UniquenessLevel::Project, "project"},
                 {UniquenessLevel::Group, "group"},
                 {UniquenessLevel::Scheme, "scheme"},
                 {UniquenessLevel::Global, "global"},
             })

JSONIFY_ENUM(MonikerKind,
             {
                 {MonikerKind::Import, "import"},
                 {MonikerKind::Export, "export"},
                 {MonikerKind::Local, "local"},
             })

JSONIFY(CancelParams, id)

JSONIFY(RegularExpressionsClientCapabilities, engine, version)

JSONIFY(Position, line, character)

JSONIFY(Command, title, command, arguments)

JSONIFY(ChangeAnnotation, label, needsConfirmation, description)

JSONIFY(CreateFileOptions, overwrite, ignoreIfExists)

JSONIFY(RenameFileOptions, overwrite, ignoreIfExists)

JSONIFY(DeleteFileOptions, recursive, ignoreIfNotExists)

JSONIFY(WorkspaceEditClientCapabilities::ChangeAnnotationSupportType, groupsOnLabel)
JSONIFY(WorkspaceEditClientCapabilities, documentChanges, resourceOperations, failureHandling, normalizesLineEndings,
        changeAnnotationSupport)

JSONIFY(DocumentFilter, language, scheme, pattern)

JSONIFY(StaticRegistrationOptions, id)

JSONIFY(MarkupContent, kind, value)

JSONIFY(MarkdownClientCapabilities, parser, version)

JSONIFY(WorkDoneProgressBegin, kind, title, cancellable, message, percentage)

JSONIFY(WorkDoneProgressReport, kind, cancellable, message, percentage)

JSONIFY(WorkDoneProgressEnd, kind, message)

JSONIFY(WorkDoneProgressOptions, workDoneProgress)

JSONIFY(InitializeError, retry)

JSONIFY_EMPTY(InitializedParams)

JSONIFY(LogTraceParams, message, verbose)

JSONIFY(SetTraceParams, value)

JSONIFY(ShowMessageParams, type, message)

JSONIFY(ShowMessageRequestClientCapabilities::MessageActionItemType, additionalPropertiesSupport)
JSONIFY(ShowMessageRequestClientCapabilities, messageActionItem)

JSONIFY(MessageActionItem, title)

JSONIFY(ShowDocumentClientCapabilities, support)

JSONIFY(ShowDocumentResult, success)

JSONIFY(LogMessageParams, type, message)

JSONIFY(Registration, id, method, registerOptions)

JSONIFY(Unregistration, id, method)

JSONIFY(WorkspaceFoldersServerCapabilities, supported, changeNotifications)

JSONIFY(DidChangeConfigurationClientCapabilities, dynamicRegistration)

JSONIFY(DidChangeConfigurationParams, settings)

JSONIFY(DidChangeWatchedFilesClientCapabilities, dynamicRegistration)

JSONIFY(FileSystemWatcher, globPattern, kind)

JSONIFY(WorkspaceSymbolClientCapabilities::SymbolKindType, valueSet)
JSONIFY(WorkspaceSymbolClientCapabilities::TagSupportType, valueSet)
JSONIFY(WorkspaceSymbolClientCapabilities, dynamicRegistration, symbolKind, tagSupport)

JSONIFY(ExecuteCommandClientCapabilities, dynamicRegistration)

JSONIFY(ApplyWorkspaceEditResponse, applied, failureReason, failedChange)

JSONIFY(FileOperationPatternOptions, ignoreCase)

JSONIFY(FileCreate, uri)

JSONIFY(FileRename, oldUri, newUri)

JSONIFY(FileDelete, uri)

JSONIFY(SaveOptions, includeText)

JSONIFY(TextDocumentSyncClientCapabilities, dynamicRegistration, willSave, willSaveWaitUntil, didSave)

JSONIFY(PublishDiagnosticsClientCapabilities::TagSupportType, valueSet)
JSONIFY(PublishDiagnosticsClientCapabilities, relatedInformation, tagSupport, versionSupport, codeDescriptionSupport,
        dataSupport)

JSONIFY(CompletionClientCapabilities::CompletionItemType::TagSupportType, valueSet)
JSONIFY(CompletionClientCapabilities::CompletionItemType::ResolveSupportType, properties)
JSONIFY(CompletionClientCapabilities::CompletionItemType::InsertTextModeSupportType, valueSet)
JSONIFY(CompletionClientCapabilities::CompletionItemType, snippetSupport, commitCharactersSupport, documentationFormat,
        deprecatedSupport, preselectSupport, tagSupport, insertReplaceSupport, resolveSupport, insertTextModeSupport)
JSONIFY(CompletionClientCapabilities::CompletionItemKindType, valueSet)
JSONIFY(CompletionClientCapabilities, dynamicRegistration, completionItem, completionItemKind, contextSupport)

JSONIFY(CompletionContext, triggerKind, triggerCharacter)

JSONIFY(HoverClientCapabilities, dynamicRegistration, contentFormat)

JSONIFY(MarkedStringFull, language, value)

JSONIFY(SignatureHelpClientCapabilities::SignatureInformationType::ParameterInformationType, labelOffsetSupport)
JSONIFY(SignatureHelpClientCapabilities::SignatureInformationType, documentationFormat, parameterInformation,
        activeParameterSupport)
JSONIFY(SignatureHelpClientCapabilities, dynamicRegistration, signatureInformation, contextSupport)

JSONIFY(DeclarationClientCapabilities, dynamicRegistration, linkSupport)

JSONIFY(DefinitionClientCapabilities, dynamicRegistration, linkSupport)

JSONIFY(TypeDefinitionClientCapabilities, dynamicRegistration, linkSupport)

JSONIFY(ImplementationClientCapabilities, dynamicRegistration, linkSupport)

JSONIFY(ReferenceClientCapabilities, dynamicRegistration)

JSONIFY(ReferenceContext, includeDeclaration)

JSONIFY(DocumentHighlightClientCapabilities, dynamicRegistration)

JSONIFY(DocumentSymbolClientCapabilities::SymbolKindType, valueSet)
JSONIFY(DocumentSymbolClientCapabilities::TagSupportType, valueSet)
JSONIFY(DocumentSymbolClientCapabilities, dynamicRegistration, symbolKind, hierarchicalDocumentSymbolSupport,
        tagSupport, labelSupport)

JSONIFY(CodeActionClientCapabilities::CodeActionLiteralSupportType::CodeActionKindType, valueSet)
JSONIFY(CodeActionClientCapabilities::CodeActionLiteralSupportType, codeActionKind)
JSONIFY(CodeActionClientCapabilities::ResolveSupportType, properties)
JSONIFY(CodeActionClientCapabilities, dynamicRegistration, codeActionLiteralSupport, isPreferredSupport,
        disabledSupport, dataSupport, resolveSupport, honorsChangeAnnotations)

JSONIFY(CodeLensClientCapabilities, dynamicRegistration)

JSONIFY(CodeLensWorkspaceClientCapabilities, refreshSupport)

JSONIFY(DocumentLinkClientCapabilities, dynamicRegistration, tooltipSupport)

JSONIFY(DocumentColorClientCapabilities, dynamicRegistration)

JSONIFY(Color, red, green, blue, alpha)

JSONIFY(DocumentFormattingClientCapabilities, dynamicRegistration)

JSONIFY_FWD(FormattingOptions)

JSONIFY(DocumentRangeFormattingClientCapabilities, dynamicRegistration)

JSONIFY(DocumentOnTypeFormattingClientCapabilities, dynamicRegistration)

JSONIFY(DocumentOnTypeFormattingOptions, firstTriggerCharacter, moreTriggerCharacter)

JSONIFY(RenameClientCapabilities, dynamicRegistration, prepareSupport, prepareSupportDefaultBehavior,
        honorsChangeAnnotations)

JSONIFY(RenameDefaultBehavior, defaultBehavior)

JSONIFY(FoldingRangeClientCapabilities, dynamicRegistration, rangeLimit, lineFoldingOnly)

JSONIFY(FoldingRange, startLine, startCharacter, endLine, endCharacter, kind)

JSONIFY(SelectionRangeClientCapabilities, dynamicRegistration)

JSONIFY(CallHierarchyClientCapabilities, dynamicRegistration)

JSONIFY(SemanticTokensLegend, tokenTypes, tokenModifiers)

JSONIFY_EMPTY(SemanticTokensClientCapabilities::RequestsType::RangeType)
JSONIFY(SemanticTokensClientCapabilities::RequestsType::FullType, delta)
JSONIFY(SemanticTokensClientCapabilities::RequestsType, range, full)
JSONIFY(SemanticTokensClientCapabilities, dynamicRegistration, requests, tokenTypes, tokenModifiers, formats,
        overlappingTokenSupport, multilineTokenSupport)

JSONIFY(SemanticTokens, resultId, data)

JSONIFY(SemanticTokensPartialResult, data)

JSONIFY(SemanticTokensEdit, start, deleteCount, data)

JSONIFY(SemanticTokensWorkspaceClientCapabilities, refreshSupport)

JSONIFY(LinkedEditingRangeClientCapabilities, dynamicRegistration)

JSONIFY(MonikerClientCapabilities, dynamicRegistration)

JSONIFY(Moniker, scheme, identifier, unique, kind)

JSONIFY(ProgressParams, token, value)

JSONIFY(Range, start, end)

JSONIFY(CodeDescription, href)

JSONIFY(CreateFile, kind, uri, options, annotationId)

JSONIFY(RenameFile, kind, oldUri, newUri, options, annotationId)

JSONIFY(DeleteFile, kind, uri, options, annotationId)

JSONIFY(TextDocumentIdentifier, uri)

JSONIFY(TextDocumentItem, uri, languageId, version, text)

JSONIFY(WorkDoneProgressParams, workDoneToken)

JSONIFY(PartialResultParams, partialResultToken)

JSONIFY(TextDocumentClientCapabilities, synchronization, completion, hover, signatureHelp, declaration, definition,
        typeDefinition, implementation, references, documentHighlight, documentSymbol, codeAction, codeLens,
        documentLink, colorProvider, formatting, rangeFormatting, onTypeFormatting, rename, publishDiagnostics,
        foldingRange, selectionRange, linkedEditingRange, callHierarchy, semanticTokens, moniker)

JSONIFY(ShowMessageRequestParams, type, message, actions)

JSONIFY(WorkDoneProgressCreateParams, token)

JSONIFY(WorkDoneProgressCancelParams, token)

JSONIFY(RegistrationParams, registrations)

JSONIFY(UnregistrationParams, unregisterations)

JSONIFY(WorkspaceFolder, uri, name)

JSONIFY(ConfigurationItem, scopeUri, section)

JSONIFY(DidChangeWatchedFilesRegistrationOptions, watchers)

JSONIFY(FileEvent, uri, type)

JSONIFY(WorkspaceSymbolOptions, workDoneProgress)

JSONIFY(ExecuteCommandOptions, commands, workDoneProgress)

JSONIFY(FileOperationPattern, glob, matches, options)

JSONIFY(CreateFilesParams, files)

JSONIFY(RenameFilesParams, files)

JSONIFY(DeleteFilesParams, files)

JSONIFY(TextDocumentSyncOptions, openClose, change, willSave, willSaveWaitUntil, save)

JSONIFY(CompletionOptions, triggerCharacters, allCommitCharacters, resolveProvider, workDoneProgress)

JSONIFY(HoverOptions, workDoneProgress)

JSONIFY(SignatureHelpOptions, triggerCharacters, retriggerCharacters, workDoneProgress)

JSONIFY(ParameterInformation, label, documentation)

JSONIFY(DeclarationOptions, workDoneProgress)

JSONIFY(DefinitionOptions, workDoneProgress)

JSONIFY(TypeDefinitionOptions, workDoneProgress)

JSONIFY(ImplementationOptions, workDoneProgress)

JSONIFY(ReferenceOptions, workDoneProgress)

JSONIFY(DocumentHighlightOptions, workDoneProgress)

JSONIFY(DocumentSymbolOptions, label, workDoneProgress)

JSONIFY(CodeActionOptions, codeActionKinds, resolveProvider, workDoneProgress)

JSONIFY(CodeLensOptions, resolveProvider, workDoneProgress)

JSONIFY(DocumentLinkOptions, resolveProvider, workDoneProgress)

JSONIFY(DocumentColorOptions, workDoneProgress)

JSONIFY(DocumentFormattingOptions, workDoneProgress)

JSONIFY(DocumentRangeFormattingOptions, workDoneProgress)

JSONIFY(RenameOptions, prepareProvider, workDoneProgress)

JSONIFY(FoldingRangeOptions, workDoneProgress)

JSONIFY(SelectionRangeOptions, workDoneProgress)

JSONIFY(CallHierarchyOptions, workDoneProgress)

JSONIFY_EMPTY(SemanticTokensOptions::RangeType)
JSONIFY(SemanticTokensOptions::FullType, delta)
JSONIFY(SemanticTokensOptions, legend, range, full, workDoneProgress)

JSONIFY(SemanticTokensDelta, resultId, edits)

JSONIFY(SemanticTokensDeltaPartialResult, edits)

JSONIFY(LinkedEditingRangeOptions, workDoneProgress)

JSONIFY(MonikerOptions, workDoneProgress)

JSONIFY(Location, uri, range)

JSONIFY(LocationLink, originSelectionRange, targetUri, targetRange, targetSelectionRange)

JSONIFY(TextEdit, range, newText)

JSONIFY(VersionedTextDocumentIdentifier, version, uri)

JSONIFY(OptionalVersionedTextDocumentIdentifier, version, uri)

JSONIFY(TextDocumentPositionParams, textDocument, position)

JSONIFY(TextDocumentRegistrationOptions, documentSelector)

JSONIFY(ClientCapabilities::WorkspaceType::FileOperationsType, dynamicRegistration, didCreate, willCreate, didRename,
        willRename, didDelete, willDelete)
JSONIFY(ClientCapabilities::WorkspaceType, applyEdit, workspaceEdit, didChangeConfiguration, didChangeWatchedFiles,
        symbol, executeCommand, workspaceFolders, configuration, semanticTokens, codeLens, fileOperations)
JSONIFY(ClientCapabilities::WindowType, workDoneProgress, showMessage, showDocument)
JSONIFY(ClientCapabilities::GeneralType, regularExpressions, markdown)
JSONIFY(ClientCapabilities, workspace, textDocument, window, general, experimental)

JSONIFY(ShowDocumentParams, uri, external, takeFocus, selection)

JSONIFY(WorkspaceFoldersChangeEvent, added, removed)

JSONIFY(ConfigurationParams, items)

JSONIFY(DidChangeWatchedFilesParams, changes)

JSONIFY(WorkspaceSymbolRegistrationOptions, workDoneProgress)

JSONIFY(WorkspaceSymbolParams, query, workDoneToken, partialResultToken)

JSONIFY(ExecuteCommandRegistrationOptions, commands, workDoneProgress)

JSONIFY(ExecuteCommandParams, command, arguments, workDoneToken)

JSONIFY(FileOperationFilter, scheme, pattern)

JSONIFY(DidOpenTextDocumentParams, textDocument)

JSONIFY(TextDocumentContentChangeEvent, range, rangeLength, text)

JSONIFY(WillSaveTextDocumentParams, textDocument, reason)

JSONIFY(DidSaveTextDocumentParams, textDocument, text)

JSONIFY(DidCloseTextDocumentParams, textDocument)

JSONIFY(InsertReplaceEdit, newText, insert, replace)

JSONIFY(Hover, contents, range)

JSONIFY(SignatureInformation, label, documentation, parameters, activeParameter)

JSONIFY(DocumentHighlight, range, kind)

JSONIFY(DocumentSymbolParams, textDocument, workDoneToken, partialResultToken)

JSONIFY(DocumentSymbol, name, detail, kind, tags, deprecated, range, selectionRange, children)

JSONIFY(CodeLensParams, textDocument, workDoneToken, partialResultToken)

JSONIFY(CodeLens, range, command, data)

JSONIFY(DocumentLinkParams, textDocument, workDoneToken, partialResultToken)

JSONIFY(DocumentLink, range, target, tooltip, data)

JSONIFY(DocumentColorParams, textDocument, workDoneToken, partialResultToken)

JSONIFY(ColorInformation, range, color)

JSONIFY(ColorPresentationParams, textDocument, color, range, workDoneToken, partialResultToken)

JSONIFY(DocumentFormattingParams, textDocument, options, workDoneToken)

JSONIFY(DocumentRangeFormattingParams, textDocument, range, options, workDoneToken)

JSONIFY(RenamePlaceHolder, range, placeholder)

JSONIFY(FoldingRangeParams, textDocument, workDoneToken, partialResultToken)

JSONIFY(SelectionRangeParams, textDocument, positions, workDoneToken, partialResultToken)

JSONIFY_FWD(SelectionRange)

JSONIFY(CallHierarchyItem, name, kind, tags, detail, uri, range, selectionRange, data)

JSONIFY(SemanticTokensParams, textDocument, workDoneToken, partialResultToken)

JSONIFY(SemanticTokensDeltaParams, textDocument, previousResultId, workDoneToken, partialResultToken)

JSONIFY(SemanticTokensRangeParams, textDocument, range, workDoneToken, partialResultToken)

JSONIFY(LinkedEditingRanges, ranges, wordPattern)

JSONIFY(DiagnosticRelatedInformation, location, message)

JSONIFY(AnnotatedTextEdit, annotationId, range, newText)

JSONIFY(InitializeParams::ClientInfoType, name, version)
JSONIFY(InitializeParams, processId, clientInfo, locale, rootPath, rootUri, initializationOptions, capabilities, trace,
        workspaceFolders, workDoneToken)

JSONIFY(DidChangeWorkspaceFoldersParams, event)

JSONIFY(FileOperationRegistrationOptions, filters)

JSONIFY(TextDocumentChangeRegistrationOptions, syncKind, documentSelector)

JSONIFY(DidChangeTextDocumentParams, textDocument, contentChanges)

JSONIFY(TextDocumentSaveRegistrationOptions, includeText, documentSelector)

JSONIFY(CompletionRegistrationOptions, documentSelector, triggerCharacters, allCommitCharacters, resolveProvider,
        workDoneProgress)

JSONIFY(CompletionParams, context, textDocument, position, workDoneToken, partialResultToken)

JSONIFY(CompletionItem, label, kind, tags, detail, documentation, deprecated, preselect, sortText, filterText,
        insertText, insertTextFormat, insertTextMode, textEdit, additionalTextEdits, commitCharacters, command, data)

JSONIFY(HoverRegistrationOptions, documentSelector, workDoneProgress)

JSONIFY(HoverParams, textDocument, position, workDoneToken)

JSONIFY(SignatureHelpRegistrationOptions, documentSelector, triggerCharacters, retriggerCharacters, workDoneProgress)

JSONIFY(SignatureHelp, signatures, activeSignature, activeParameter)

JSONIFY(DeclarationRegistrationOptions, workDoneProgress, documentSelector, id)

JSONIFY(DeclarationParams, textDocument, position, workDoneToken, partialResultToken)

JSONIFY(DefinitionRegistrationOptions, documentSelector, workDoneProgress)

JSONIFY(DefinitionParams, textDocument, position, workDoneToken, partialResultToken)

JSONIFY(TypeDefinitionRegistrationOptions, documentSelector, workDoneProgress, id)

JSONIFY(TypeDefinitionParams, textDocument, position, workDoneToken, partialResultToken)

JSONIFY(ImplementationRegistrationOptions, documentSelector, workDoneProgress, id)

JSONIFY(ImplementationParams, textDocument, position, workDoneToken, partialResultToken)

JSONIFY(ReferenceRegistrationOptions, documentSelector, workDoneProgress)

JSONIFY(ReferenceParams, context, textDocument, position, workDoneToken, partialResultToken)

JSONIFY(DocumentHighlightRegistrationOptions, documentSelector, workDoneProgress)

JSONIFY(DocumentHighlightParams, textDocument, position, workDoneToken, partialResultToken)

JSONIFY(DocumentSymbolRegistrationOptions, documentSelector, label, workDoneProgress)

JSONIFY(SymbolInformation, name, kind, tags, deprecated, location, containerName)

JSONIFY(CodeActionRegistrationOptions, documentSelector, codeActionKinds, resolveProvider, workDoneProgress)

JSONIFY(CodeLensRegistrationOptions, documentSelector, resolveProvider, workDoneProgress)

JSONIFY(DocumentLinkRegistrationOptions, documentSelector, resolveProvider, workDoneProgress)

JSONIFY(DocumentColorRegistrationOptions, documentSelector, id, workDoneProgress)

JSONIFY(ColorPresentation, label, textEdit, additionalTextEdits)

JSONIFY(DocumentFormattingRegistrationOptions, documentSelector, workDoneProgress)

JSONIFY(DocumentRangeFormattingRegistrationOptions, documentSelector, workDoneProgress)

JSONIFY(DocumentOnTypeFormattingRegistrationOptions, documentSelector, firstTriggerCharacter, moreTriggerCharacter)

JSONIFY(DocumentOnTypeFormattingParams, ch, options, textDocument, position)

JSONIFY(RenameRegistrationOptions, documentSelector, prepareProvider, workDoneProgress)

JSONIFY(RenameParams, newName, textDocument, position, workDoneToken)

JSONIFY(PrepareRenameParams, textDocument, position)

JSONIFY(FoldingRangeRegistrationOptions, documentSelector, workDoneProgress, id)

JSONIFY(SelectionRangeRegistrationOptions, workDoneProgress, documentSelector, id)

JSONIFY(CallHierarchyRegistrationOptions, documentSelector, workDoneProgress, id)

JSONIFY(CallHierarchyPrepareParams, textDocument, position, workDoneToken)

JSONIFY(CallHierarchyIncomingCallsParams, item, workDoneToken, partialResultToken)

JSONIFY(CallHierarchyIncomingCall, from, fromRanges)

JSONIFY(CallHierarchyOutgoingCallsParams, item, workDoneToken, partialResultToken)

JSONIFY(CallHierarchyOutgoingCall, to, fromRanges)

JSONIFY(SemanticTokensRegistrationOptions, documentSelector, legend, range, full, workDoneProgress, id)

JSONIFY(LinkedEditingRangeRegistrationOptions, documentSelector, workDoneProgress, id)

JSONIFY(LinkedEditingRangeParams, textDocument, position, workDoneToken)

JSONIFY(MonikerRegistrationOptions, documentSelector, workDoneProgress)

JSONIFY(MonikerParams, textDocument, position, workDoneToken, partialResultToken)

JSONIFY(Diagnostic, range, severity, code, codeDescription, source, message, tags, relatedInformation, data)

JSONIFY(TextDocumentEdit, textDocument, edits)

JSONIFY(ServerCapabilities::WorkspaceType::FileOperationsType, didCreate, willCreate, didRename, willRename, didDelete,
        willDelete)
JSONIFY(ServerCapabilities::WorkspaceType, workspaceFolders, fileOperations)
JSONIFY(ServerCapabilities, textDocumentSync, completionProvider, hoverProvider, signatureHelpProvider,
        declarationProvider, definitionProvider, typeDefinitionProvider, implementationProvider, referencesProvider,
        documentHighlightProvider, documentSymbolProvider, codeActionProvider, codeLensProvider, documentLinkProvider,
        colorProvider, documentFormattingProvider, documentRangeFormattingProvider, documentOnTypeFormattingProvider,
        renameProvider, foldingRangeProvider, executeCommandProvider, selectionRangeProvider,
        linkedEditingRangeProvider, callHierarchyProvider, semanticTokensProvider, monikerProvider,
        workspaceSymbolProvider, workspace, experimental)

JSONIFY(CompletionList, isIncomplete, items)

JSONIFY(SignatureHelpContext, triggerKind, triggerCharacter, isRetrigger, activeSignatureHelp)

JSONIFY(WorkspaceEdit::ChangesType, propertyMap)

JSONIFY_FWD(WorkspaceEdit::ChangeAnnotationsType)
JSONIFY(WorkspaceEdit, changes, documentChanges, changeAnnotations)

JSONIFY(InitializeResult::ServerInfoType, name, version)
JSONIFY(InitializeResult, capabilities, serverInfo)

JSONIFY(PublishDiagnosticsParams, uri, version, diagnostics)

JSONIFY(SignatureHelpParams, context, textDocument, position, workDoneToken)

JSONIFY(CodeActionContext, diagnostics, only)

JSONIFY(ApplyWorkspaceEditParams, label, edit)

JSONIFY(CodeActionParams, textDocument, range, context, workDoneToken, partialResultToken)

JSONIFY(CodeAction::DisabledType, reason)
JSONIFY(CodeAction, title, kind, diagnostics, isPreferred, disabled, edit, command, data)

}
